### ISSUE TITLE
start_fmg.sh - config drive

### ISSUE THREAD

**Issue by gauravsabharwal** [fortinet-solutions-cse/testbeds#1]
There are two issues:

1. Line 60 has trailing "license", which shouldn't be there.

2. The config drive based configuration doesn't work. What are the ways to troubleshoot? On FortiGate, I have successfully used "diag debug cloudinit show" in the past, but that command doesn't seem to be available on FMG.

**Comment by mamunozgonzalez** [comment]
Hi,
I just fixed the typo in line 60.
Regarding config drive, you are right it does not work at the moment. A new request to include this feature in FMG has been requested.

Thanks!
